"""Trigonometry tools for angles, identities, and triangle solving."""

from mathcore.trigonometry.functions import (
    sin,
    cos,
    tan,
    csc,
    sec,
    cot,
    asin,
    acos,
    atan,
    radians,
    degrees,
    normalize_angle_radians,
    normalize_angle_degrees,
    unit_circle_point,
    taylor_sin,
    taylor_cos,
)
from mathcore.trigonometry.triangles import (
    pythagorean_hypotenuse,
    pythagorean_leg,
    law_of_sines_side,
    law_of_sines_angle,
    law_of_cosines_side,
    law_of_cosines_angle,
    triangle_area_sas,
    triangle_area_heron,
)
from mathcore.trigonometry.identities import (
    verify_pythagorean_identity,
    verify_sum_difference_identity,
    verify_double_angle_identity,
)

__all__ = [
    "sin",
    "cos",
    "tan",
    "csc",
    "sec",
    "cot",
    "asin",
    "acos",
    "atan",
    "radians",
    "degrees",
    "normalize_angle_radians",
    "normalize_angle_degrees",
    "unit_circle_point",
    "taylor_sin",
    "taylor_cos",
    "pythagorean_hypotenuse",
    "pythagorean_leg",
    "law_of_sines_side",
    "law_of_sines_angle",
    "law_of_cosines_side",
    "law_of_cosines_angle",
    "triangle_area_sas",
    "triangle_area_heron",
    "verify_pythagorean_identity",
    "verify_sum_difference_identity",
    "verify_double_angle_identity",
]
